version = 0.1

[default.build.parameters]
use_container = true
mount_with = "WRITE"

[default.deploy.parameters]
stack_name = "tournament-manager"
resolve_s3 = true
s3_prefix = "tournament-manager"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = [
    "SecretArn=arn:aws:secretsmanager:eu-west-1:327362716042:secret:tournament-manager-t46p79",
    "S3AssetsBucket=lockout-tournament-assets",
    "SecretVersion=1.2",
    "RestartDBInstanceId=i-04694c0408ed2540e"
]
image_repositories = []
